### ISSUE TITLE
Bad OSGI Manifest

### ISSUE THREAD

**Issue by rimmeraj** [akarnokd/RxJavaBridge#66]
In a pure osgi environment the MANIFEST.MF does not export any packages and thus nothing is visible.

Private-Package: hu.akarnokd.rxjava3.bridge

S/B

Export-Package: hu.akarnokd.rxjava3.bridge

**Comment by akarnokd** [comment]
Fixed via https://github.com/akarnokd/RxJavaBridge/commit/bb66cdd4717926e8520434c6b63cbe8fa07c6344 and [3.0.1](https://github.com/akarnokd/RxJavaBridge/releases/tag/v3.0.1)
