### ISSUE TITLE
More bad OSGI manifest entries

### ISSUE THREAD

**Issue by rimmeraj** [akarnokd/RxJavaBridge#67]
You are trying to import ....

io.reactivex.rxjava3.internal.disposables

In rxjava3 it is private..

**Comment by akarnokd** [comment]
Closing via https://github.com/akarnokd/RxJavaBridge/commit/ca8bcc13bfdd873e043c760d6919ee96b10f2397 and [v3.0.2](https://github.com/akarnokd/RxJavaBridge/releases/tag/v3.0.2).
